export const data = [
  {
    id: 1,
    task: "PARMESAN SHAKERS",
    completed: false,
    visible: false,
    lastSign: "1",
  },
  {
    id: 2,
    task: "PEPPER SHAKERS",
    completed: false,
    visible: false,
    lastSign: "1",
  },
  {
    id: 3,
    task: "ARTICHOKES",
    completed: false,
    visible: false,
    lastSign: "1",
  },
  {
    id: 4,
    task: "BLEU CHEESE",
    completed: false,
    visible: false,
    lastSign: "1",
  },
  {
    id: 5,
    task: "BEETS",
    completed: false,
    visible: false,
    lastSign: "1",
  },
  {
    id: 6,
    task: "BROCCOLI",
    completed: false,
    visible: false,
    lastSign: "1",
  },
  {
    id: 7,
    task: "CARROTS",
    completed: false,
    visible: false,
    lastSign: "1",
  },
  {
    id: 8,
    task: "CORN",
    completed: false,
    visible: false,
    lastSign: "1",
  },
  {
    id: 9,
    task: "GARBONZO BEANS",
    completed: false,
    visible: false,
    lastSign: "1",
  },
  {
    id: 10,
    task: "MUSHROOMS",
    completed: false,
    visible: false,
    lastSign: "1",
  },
  {
    id: 11,
    task: "JALAPENOS",
    completed: false,
    visible: false,
    lastSign: "1",
  },
  {
    id: 12,
    task: "MUSHROOMS",
    completed: false,
    visible: false,
    lastSign: "1",
  },
  {
    id: 13,
    task: "OLIVES",
    completed: false,
    visible: true,
    lastSign: "1",
  },
  {
    id: 14,
    task: "OLIVE TUB",
    completed: false,
    visible: true,
    lastSign: "1",
  },
  {
    id: 15,
    task: "PEAS",
    completed: false,
    visible: false,
    lastSign: "1",
  },
  {
    id: 16,
    task: "PICKLES",
    completed: false,
    visible: false,
    lastSign: "1",
  },
  {
    id: 17,
    task: "PINEAPPLE",
    completed: false,
    visible: false,
    lastSign: "1",
  },
  {
    id: 18,
    task: "SPINACH",
    completed: false,
    visible: false,
    lastSign: "1",
  },
  {
    id: 19,
    task: "TIM'S ONIONS",
    completed: false,
    visible: false,
    lastSign: "1",
  },
  {
    id: 20,
    task: "TIM'S TOMATOES",
    completed: false,
    visible: false,
    lastSign: "1",
  },
  {
    id: 21,
    task: "BAG HOT WINGS 12 OZ",
    completed: false,
    visible: true,
    lastSign: "1",
  },
  {
    id: 22,
    task: "CHIX TENDERS",
    completed: false,
    visible: true,
    lastSign: "1",
  },
  {
    id: 23,
    task: "POT.SKINS",
    completed: false,
    visible: true,
    lastSign: "1",
  },
  {
    id: 24,
    task: "LASAGNA",
    completed: false,
    visible: false,
    lastSign: "1",
  },
  {
    id: 25,
    task: "MAC & CHEESE",
    completed: false,
    visible: false,
    lastSign: "1",
  },
  {
    id: 26,
    task: "GARLIC BREAD",
    completed: false,
    visible: false,
    lastSign: "1",
  },
  {
    id: 27,
    task: "BACON",
    completed: false,
    visible: false,
    lastSign: "1",
  },
  {
    id: 28,
    task: "FILL APPLE CUPS",
    completed: false,
    visible: false,
    lastSign: "1",
  },
  {
    id: 29,
    task: "APPLE CRUMB MIX",
    completed: false,
    visible: false,
    lastSign: "1",
  },
  {
    id: 30,
    task: "MARINATE CHICKEN",
    completed: false,
    visible: false,
    lastSign: "1",
  },
  {
    id: 31,
    task: "COOK/CUT CHICKEN",
    completed: false,
    visible: true,
    lastSign: "1",
  },
  {
    id: 32,
    task: "CUT LA HOT",
    completed: false,
    visible: false,
    lastSign: "1",
  },
  {
    id: 33,
    task: "2 OZ RANCH CUPS",
    completed: false,
    visible: false,
    lastSign: "1",
  },
  {
    id: 34,
    task: "4 OZ RANCH CUPS",
    completed: false,
    visible: false,
    lastSign: "1",
  },
  {
    id: 35,
    task: "8 OZ LARGE RANCH",
    completed: false,
    visible: false,
    lastSign: "1",
  },
  {
    id: 36,
    task: "SOUR CREAM CUPS",
    completed: false,
    visible: false,
    lastSign: "1",
  },
  {
    id: 37,
    task: "4 OZ PIZZA CUPS",
    completed: false,
    visible: false,
    lastSign: "1",
  },
  {
    id: 38,
    task: "BURGER PATTY 5.5 OZ",
    completed: false,
    visible: false,
    lastSign: "1",
  },
  {
    id: 39,
    task: "SLICE MUSHROOMS",
    completed: false,
    visible: true,
    lastSign: "1",
  },
  {
    id: 40,
    task: "SLICE BELL PEPPERS",
    completed: false,
    visible: true,
    lastSign: "1",
  },
  {
    id: 41,
    task: "SLICE ONIONS",
    completed: false,
    visible: true,
    lastSign: "1",
  },
  {
    id: 42,
    task: "SLICE TOMATOES",
    completed: false,
    visible: true,
    lastSign: "1",
  },
  {
    id: 43,
    task: "DELI LETTUCE",
    completed: false,
    visible: false,
    lastSign: "1",
  },
  {
    id: 44,
    task: "SLICE RED ONIONS",
    completed: false,
    visible: false,
    lastSign: "1",
  },
  {
    id: 45,
    task: "SLICE CUCUMBERS",
    completed: false,
    visible: false,
    lastSign: "1",
  },
  {
    id: 46,
    task: "SLICE ZUCCHINI",
    completed: false,
    visible: false,
    lastSign: "1",
  },
  {
    id: 47,
    task: "SLICE/BAG PASTRAMI",
    completed: false,
    visible: false,
    lastSign: "1",
  },
  {
    id: 48,
    task: "SLICE/BAG TURKEY",
    completed: false,
    visible: false,
    lastSign: "1",
  },
  {
    id: 49,
    task: "MOZZARELLA CHEESE",
    completed: false,
    visible: false,
    lastSign: "1",
  },
  {
    id: 50,
    task: "MOZZ/CHEDDAR BLEND",
    completed: false,
    visible: false,
    lastSign: "1",
  },
  {
    id: 51,
    task: "SLICE SWISS",
    completed: false,
    visible: false,
    lastSign: "1",
  },
  {
    id: 52,
    task: "PIZZA SAUCE",
    completed: false,
    visible: true,
    lastSign: "1",
  },
  {
    id: 53,
    task: "TIM'S SAUCE",
    completed: false,
    visible: false,
    lastSign: "1",
  },
  {
    id: 54,
    task: "GARLIC WHITE SAUCE",
    completed: false,
    visible: false,
    lastSign: "1",
  },
  {
    id: 55,
    task: "BREADSTICK MIX",
    completed: false,
    visible: false,
    lastSign: "1",
  },
  {
    id: 56,
    task: "RANCH DRESSING",
    completed: false,
    visible: false,
    lastSign: "1",
  },
  {
    id: 57,
    task: "FILL GWS JUGS",
    completed: false,
    visible: false,
    lastSign: "1",
  },
  {
    id: 58,
    task: "FILL BBQ JUGS",
    completed: false,
    visible: false,
    lastSign: "1",
  },
  {
    id: 59,
    task: "THAW PESTO",
    completed: false,
    visible: false,
    lastSign: "1",
  },
  {
    id: 60,
    task: "THAW LA HOT",
    completed: false,
    visible: false,
    lastSign: "1",
  },
  {
    id: 61,
    task: "THAW VEGAN CHEESE",
    completed: false,
    visible: false,
    lastSign: "1",
  },
  {
    id: 62,
    task: "THAW FETA CHEESE",
    completed: false,
    visible: false,
    lastSign: "1",
  },
  {
    id: 63,
    task: "THAW BLEU CHEESE",
    completed: false,
    visible: false,
    lastSign: "1",
  },
  {
    id: 64,
    task: "THAW CAULIFLOWER/GF",
    completed: false,
    visible: false,
    lastSign: "1",
  },
];

export const newData = data.map((task, index) => {
  return {
    id: index + 1,
    task,
    completed: false,
    visible: true,
    lastSign: "1",
  };
});
